# Developed by: Eng. Mouaz M. Al-Shahmeh
name: quran_flutter_app
description: Developed by Eng Mouaz M AlShahmeh
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flutter_lints: ^1.0.0
  provider: 6.0.2
  shared_preferences: ^2.0.15
  audioplayers: ^1.0.1
  flutter_local_notifications: ^9.5.1
  connectivity_plus: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Questv
      fonts:
        - asset: assets/fonts/Questv-Regular.otf
        - asset: assets/fonts/Questv-bold.otf
